#用户注册
POST http://localhost:8101/api/register/create HTTP/1.1
#POST http://oa.chinahuian.cn/platform/user/register/create HTTP/1.1
content-type: application/json
Accept: application/json

{
  "xm": "张三丰",
  "xb": "男",
  "sfzh": "1234567890",
  "password": "123456",
  "contact": {
    "phone": "13500000000",
    "email": "10000@qq.com",
    "qq": "10000",
    "weixin": "zsf",
    "postcode": "000000",
    "address": "湖北省武当山"
  },
  "account": {
    "type": "mobile",
    "account": "13500000000"
  }
}

###
#信息修改
POST http://localhost:7001/api/register/update?_id=5a9e3ef64ab68b0f8c9f481d HTTP/1.1
#POST http://oa.chinahuian.cn/platform/user/register/update?_id=5a741e52ddccf17e5562d188 HTTP/1.1
content-type: application/json
Accept: application/json

{
  "contact.phone": "13500000000",
  "contact.email": "zhangsanfeng@qq.com",
  "contact.qq": "10000",
  "contact.weixin": "zhangsanfeng",
  "contact.postcode": "000000",
  "contact.address": "湖北省武当山"
}

