#用户注册
#POST http://localhost:7001/member/passwd?_id=5a7418ce838df436947d7aa6 HTTP/1.1
POST http://oa.chinahuian.cn/platform/user/member/passwd?_id=5a741e52ddccf17e5562d188 HTTP/1.1
content-type: application/json
Accept: application/json

{
  "oldpass": "123456",
  "newpass": "654321"
}
